//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGAP.ACL {
    
    
    public partial class AddNewUserToGroup {
        
        /// <summary>
        /// uc_AddNewUserToGroup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebGAP.ACL.Popup.uc_AddNewUserToGroup uc_AddNewUserToGroup;
    }
}
