//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGAP.ACL {
    
    
    public partial class IndividualSet_Users {
        
        /// <summary>
        /// uc_Individualset_Users control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebGAP.ACL.uc.uc_Individualset_Users uc_Individualset_Users;
    }
}
