//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGAP.ACL {
    
    
    public partial class IndividualSet_Group {
        
        /// <summary>
        /// uc_IndividualSet_Group control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebGAP.ACL.uc.uc_IndividualSet_Group uc_IndividualSet_Group;
    }
}
