//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGAP.PhenBook {
    
    
    public partial class OMIM_Gene {
        
        /// <summary>
        /// uc_OMIM_Gene control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebGAP.PhenBook.PopUp.uc_OMIM_Gene uc_OMIM_Gene;
    }
}
