//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGAP.GAP.Trio
{


    public partial class TrioVariant_Filter
    {

        /// <summary>
        /// uc_TrioVariant_Filter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebGAP.GAP.Trio.uc.uc_TrioVariant_Filter uc_TrioVariant_Filter;
    }
}
