//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGAP.Management {
    
    
    public partial class AskDatasetPermission_Sample {
        
        /// <summary>
        /// uc_AskDatasetPermission_Sample control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebGAP.Management.Popup.uc_AskDatasetPermission_Sample uc_AskDatasetPermission_Sample;
    }
}
