//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGAP.GAP {
    
    
    public partial class Variant_Discovery {
        
        /// <summary>
        /// uc_Variant_Discovery1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebGAP.GAP.uc.uc_Variant_Discovery uc_Variant_Discovery1;
    }
}
