//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGAP.Admin
{


    public partial class SamplesheetLog_detail
    {

        /// <summary>
        /// uc_SamplesheetLog_detail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebGAP.Admin.Popup.uc_SamplesheetLog_detail uc_SamplesheetLog_detail;
    }
}
