//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGAP.GAP.CS {
    
    
    public partial class CSVariant_Filter {
        
        /// <summary>
        /// uc_CSVariant_Filter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebGAP.GAP.CS.uc.uc_CSVariant_Filter uc_CSVariant_Filter;
    }
}
